server: 
    port: 5010
spring: 
    application: 
      name: eureka-gateway

eureka: 
    client: 
      serviceUrl: 
         defaultZone: http://localhost:1111/eureka/
zuul: 
  host: 
    maxTotalConnections: 2048
    maxPerRouteConnections: 1024
  routes: 
    eureka-payment: 
      path: /payment/**
      serviceId: eureka-payment
    eureka-product: 
      path: /product/**
      serviceId: eureka-product
    eureka-user: 
      path: /user/**
      serviceId: eureka-user
