spring:
  data:
    elasticsearch:
      # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: zjq
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 127.0.0.1:9300
      repositories:
        #是否开启本地存储
        enable: true
  rabbitmq:
    host: localhost
    password: ENC(GUsLCYdW+gcOhlxhtVtfvw==)
    port: 5672
    username: ENC(GUsLCYdW+gcOhlxhtVtfvw==)
version: 2.0

