spring:
  sleuth:
    sampler:
      #链路采集率, 默认为10%
      percentage: 0.1
  zipkin:
    #zipkin地址
    base-url: http://localhost:9411
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #服务健康检查url
        healthCheckPath: ${server.servlet.context-path}/health
        #服务健康检查频率
        healthCheckInterval: 5s
        instance-id: ${spring.application.name}-${server.port}
        tags: qg=xqz, baz
        prefer-ip-address: true
        #健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 5s
      config:
        format: yaml
        enabled: true
        data-key: data
        prefix: config
        name: ${spring.application.name}/${tag}
  rabbitmq:
    host: localhost
    password: ENC(GUsLCYdW+gcOhlxhtVtfvw==)
    port: 5672
    username: ENC(GUsLCYdW+gcOhlxhtVtfvw==)
init-db: true
server:
  servlet:
    context-path: /product